backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  media_folder: "_site/images/uploads"
  media_library: 
  - name: uploads
  public_folder: "/images/uploads"
collections:
  - name: "contact"
    label: "contact"
    folder: "src/contact" 
    create: false  # Voir si faux comme ça pas de nouveau !
    slug: "{{slug}}" 
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "base_contact.njk"}
      - {label: "Adresse", name: "nom_adresse", widget: "markdown"}
      - {label: "Mail", name: "mail", widget: "url"} #A verifier si pas string
      - {label: "Instagram", name: "instagram_link", widget: "url"} # Voir pour les liens !
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/contact.njk"} # A checker !

